### PR TITLE
 Mention new features in 3.0 and update the reference manual

### LINKED ISSUE #3: Update "Features" with changes between 2.0..2.3
Unresolved questions: should we mention the version number in every line? Or should we just copy `features.pl` to, say, `features-2.0.pl`, and add a selector? It seems odd to remove the documentation for old versions forever.

### LINKED ISSUE #4: Update mentions of "Import / Assemble" to "Link / Assemble"
Same concerns as #3.

### LINKED ISSUE #5: Update "Reference" with every new feature added since 2.0

### PR DESCRIPTION
**Pull request by ruevs**
... with length difference

### CODE REVIEW

**Review by jwesthues — APPROVED** [review]
Thanks, makes sense. Please feel free to commit this and any other such incremental and obviously beneficial changes, no need for approval from me (though always glad to review if in doubt, of course).

**Review by phkahler — APPROVED** [review]
Looks good. The import->link change is a very good idea, since the menu says "link" and import is what we do with things like DXF where it more or less converts those entities into ours.

**Comment by ruevs** [comment]
Whitequark reminded me here https://github.com/solvespace/solvespace-web/issues/4.
Also we should think about changing the "Edit | Rotate Imported 90°" option to "Rotate Linked 90°" in the menu.

**Comment by phkahler** [comment]
CI failure? Wonder if I broke one of those.

**Comment by phkahler** [comment]
@jwesthues  Are the CI failures normal here?

**Comment by jwesthues** [comment]
Looks like we have:

* Warnings for links that point to redirects. We should fix those eventually, but not directly a problem.

* An error because `forum.pl` doesn't exist. That's because it isn't checked in, because it has some hard-coded secrets and messy dependencies.

So I don't think you broke anything, and I suspect the CI was failing before too. Perhaps easiest just to suppress any errors from `forum.pl`.

**Pull request merged**
