### PR TITLE
Add screenshots for reference from AppStream metadata

### PR DESCRIPTION
**Pull request by rpavlik**
The appstream metadata (used by flatpak/flathub and others) needs at least one screenshot, and they want the default one to show the full window in a 16x9 aspect ratio using a default style on Linux. None of the existing ones fit that criteria.

### CODE REVIEW

**Comment by phkahler** [comment]
You're just adding screenshots but not using them on the web site right?

**Comment by rpavlik** [comment]
Right, not using them anywhere on the web site yet. They'll show up on flathub, etc.

**Comment by phkahler** [comment]
I don't recall, do we need to run "make" on the other changes? I just (shame on me) directly edited the DL page to unbold 3.0 in the PL file.

**Comment by rpavlik** [comment]
No idea, sorry, think this is actually my first time poking the web site.

**Comment by jwesthues** [comment]
I think there is (was?) some kind of CI/CD path involving make for solvespace.github.io as a testing environment, but I'm not sure. It doesn't seem to be connected now, at least.

The live solvespace.com website doesn't update until someone manually pulls, as I just did. @phkahler If you want access to pull yourself then please just email a public ssh key, and I'll set you up.

**Comment by ruevs** [comment]
@phkahler @jwesthues There in an ["Environment"](https://github.com/solvespace/solvespace-web/deployments) that "deploys" to https://solvespace.github.io/solvespace-web/.

However it was last deployed by [@whitequark](https://github.com/whitequark) on Nov 24, 2018. I fond the [documentation on "environments"](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment) but at least I do not have access to the options described.

[This](https://github.com/solvespace/solvespace-web/blob/master/.travis.yml) seems to be the Travis configuration that was doing it but I have no idea how.

I locally run `make` when I change the site and test the generated html.

**Pull request merged**
