### PR TITLE
Add links to packaging status and PPA

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ruevs** [comment]
A definite no for me on this one. The firstbt two links are just something we will have to maintain and give information anyone can find in 30s with a search. And the "unofficial" build one is even more put of place.

**Comment by ghost** [comment]
> The firstbt two links are just something we will have to maintain and give information anyone can find in 30s with a search.

Why users should use Google to search what is the packaging state is?

It is better to add reference links to "Repology" and "Package Search" directly on SolveSpace download page.

> And the "unofficial" build one is even more put of place.

As there are NO official PPA yet and other distros still provide outdated builds, lets users be aware of 3rd-party/unofficial PPA where they can grab fresh SolveSpace DEB's.

BTW, I use @AlexanderP's PPA for years under Debian.

Additionally, link to build instruction is outdated as it points to `2.x` branch.

@jwesthues, I highly recommend to update download page with this patch — users should not use Google to search where they could get latest/fresh SolveSpace DEB builds.

**Comment by ruevs** [comment]
Since the link to https://notesalexp.org/packages/en/source/solvespace/ is now in the readme together with all other ways to get SolveSpace I will close this.
https://github.com/solvespace/solvespace/blob/master/README.md#via-third-party-packages

**Comment by ghost** [comment]
> Since the link to https://notesalexp.org/packages/en/source/solvespace/ is now in the readme together with all other ways to get SolveSpace I will close this.

To be honest, most of common users just visits ["Download" page](https://solvespace.com/download.pl) on SolveSpace website (where for Linux users only Snap & build from source options mentioned) and never visits GitHub and even reads `README.md`.

I argue to reopen and merge.

**Comment by ruevs** [comment]
Linux users so "common" that they would not visit the GitHub page should be using the official releases. What is more, the the Snap Store has an edge version that is always the latest master.

**Pull request closed without merging**
